### ISSUE TITLE
Consolidate docs into knowledge base

### ISSUE THREAD

**Issue by jamalv** [teamforus/docs#1]
- [x] https://github.com/teamforus/me/tree/develop/docs/standards
- [x] https://github.com/teamforus/forus/tree/dev/docs
- [x] https://github.com/teamforus/foundation/tree/develop/docs
- [x] https://github.com/teamforus/foundation/wiki

**Comment by jamalv** [comment]
this is the first version foundation knowledge base (it is a repo with commit history)

[foundation-knowledge-base.zip](https://github.com/teamforus/knowledge-base/files/2223689/foundation-knowledge-base.zip)

**Comment by maxvisser** [comment]
added all content, we can now start organizing.
