### ISSUE TITLE
Direct commits

### ISSUE THREAD

**Issue by maartenfv** [teamforus/docs#10]
I am currently able to directly commit to our docs and it will show up on the website.

[NEWS](https://local.theonion.com/man-knows-in-reality-marrying-minnie-mouse-wouldn-t-be-1828142524)

**Comment by maxvisser** [comment]
i fixed this by making dev a protected branch. You now need to make a pull request and then a reviewer will merge all new additions

**Comment by maxvisser** [comment]
great NEWS btw

**Comment by maxvisser** [comment]
Do you think the man will ever wake up from his dream of marying minie mouse? @GerbenBosschieter

**Comment by GerbenBosschieter** [comment]
No I don't think he will wake up from this dream. If he is already dreaming things like this, he is beyond help.

**Comment by maxvisser** [comment]
Lets all wake up. I will close this issue.
