### ISSUE TITLE
Create a standard for Markdown files

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/docs#11]
Our documentation is going be shown on the docs-website.
We should think of a standard of writing markdown files. 

This wil prevent a cluttered overview and  will result in a more read-friendly experience.
After we made a decision we should inform everybody who wil contribute to docs-files and write a guide for it.

**Comment by maartenfv** [comment]
How can we get started with this issue? How can I contribute?

**Comment by jamalv** [comment]
Inspiration: 
https://rocket.chat/docs/contributing/documentation/markdown-styleguide/

**Comment by maxvisser** [comment]
the one from rocket.chat is really nice. I think we can enforce alot of those style rules.

**Comment by jamalv** [comment]
added the one from rocket.chat: https://docs.forus.io/en/knowledge-base/contributing/markdown-styleguide/
