### ISSUE TITLE
Create a collapsible content option for the FAQ markdown

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/docs#17]

**Comment by GerbenBosschieter** [comment]
Found a solution:
https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-collapse-markdown#header-3-4

I will research the possibilities to implement this. Should be pretty easy

**Comment by maxvisser** [comment]
It seems that your solution uses userscript and therefore can only be used by installing that extension.

**Comment by jamalv** [comment]
Do we still need this now that we implemented the new docs site from rocket.chat?
