### ISSUE TITLE
technical vs organisation docs on the new website

### ISSUE THREAD

**Issue by danrminds** [teamforus/docs#22]
# Problem
We have currently 3 types of documentation that we want to feature on the new website 

- Organisational (public) 
- Organisational (internal) - there was a proposition to make it available only after logging in
- Technical documentation (currently on Apiary)

## Proposed solution 
I propose to separate these a little. First of all would separate the technical documentation (API) in a different URL - develop.forus.io / dev.forus.io instead of the same docs.forus.io. This documentation is meant for developers only or organisations that want to use our public and open source development to implement it separately. This has nothing to do with the organisational documentation we feature now on the docs.forus.io (vision, etc). 

## Possible additions
About internal and public organisational documentation - I want to see if github can show the private repositories if you are logged in on github in the same browser. More research here needed.

**Comment by maxvisser** [comment]
I was also thinking about this. I thought docs.forus.io should be the technical docs. and foundation.forus.io the non-technical website.

We can start just putting all the documentation, technical and organisational, in docs and after that show them seperately on different websites.

**Comment by jamalv** [comment]
Agreed, and indeed, lets first not worry about this separation too much and create the content first. 

For the urls, I would propose something like about.forus.io and docs.forus.io

About the internal docs, we now have https://docs-internal.forus.io which is linked to a private repo on our GitHub.

**Comment by maxvisser** [comment]
I think until we have content for the technical docs we can close this one and iterate on docs.forus.io first.
