### ISSUE TITLE
Add language (nl)

### ISSUE THREAD

**Issue by jamalv** [teamforus/docs#39]
Right now all docs are in English, we also have a dutch audience, can we support dutch?

**Comment by maxvisser** [comment]
implemented this feature on language_update 

https://github.com/teamforus/docs.forus.io/tree/language_update

**Comment by jamalv** [comment]
Yea, agree that the second option would be better. Having many branches might get confusing. Also it’s easier not having to switch branch when working on multiple languages.

**Comment by maxvisser** [comment]
I could start implementing this asap; we can start with creating a dutch branch in this repository; if all current documentation is translated to dutch we can start deploying the dutch version

**Comment by maxvisser** [comment]
As discussed I reordered the readme's in a pull request https://github.com/teamforus/docs/pull/47
