### ISSUE TITLE
I can not contribute to the contributing page.

### ISSUE THREAD

**Issue by maartenfv** [teamforus/docs#54]
When clicking on the contribute button at the bottom of the EN page it gives me an 404 error.

**Comment by jamalv** [comment]
@maxvisser this seems to have to do with the localisation.

**Comment by maxvisser** [comment]
yes this is an issue for docs.forus.io

**Comment by maxvisser** [comment]
fixed https://github.com/teamforus/docs.forus.io/commit/126550521f71c144e1ca9c52df770bc785c71f10
