### ISSUE TITLE
Matching URL for knowledge base

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/docs#7]
What:
Set the URL to : https://docs.forus.io.

How:
- create a CNAME file (doable within GitHub pages) with the domain name
- Configure ANAME with our DNS provider

**Comment by jamalv** [comment]
If you can make this more concrete, I can help with this.

**Comment by maxvisser** [comment]
I fixed docs.forus.io together with the help of Gerben. Its currently working.

**Comment by GerbenBosschieter** [comment]
Mac fixed it
